### ISSUE TITLE
[Question] Road slab, and stair

### ISSUE THREAD

**Issue by Sunrage** [powercrystals/MineFactoryReloaded#141] opened 2013-05-28 15:10 UTC
Hi, sorry for the disturb

I love your mods, it's very  useful, but can you add  slab and stair road^^  ? ( normal and  illumined )  for the decoration it's perfect 

Thx by advance and continue !

**Comment by powercrystals** [comment] 2013-05-28 22:14
I do not want to add them myself because non-"full" blocks cannot be slippery. You can make these yourself with immibis' microblocks mod, however, which I recommend you use anyway.

Closing due to not a bug.

**Closed as completed by powercrystals** 2013-05-28 22:14 UTC
