### ISSUE TITLE
RedNet Controller not working in other worlds on servers

### ISSUE THREAD

**Issue by BarelyAPrincess** [powercrystals/MineFactoryReloaded#91] opened 2013-05-06 07:58 UTC
Version: 2.5.4-665 (Tekkit 1.0.3) (Can't try any later versions since this is the one shipped with the modpack.)

On a SERVER using a bukkit multi-world managing plugin (Multiverse, Multiworld, MCWorlds) via MCPC+ (1.5.1-R0.3-SNAPSHOT), The RedNet Controllers will not operate as expected if placed in any world created/loaded by said plugins.

Steps Taken:
1. Create or load any generic/default world using MCPC+ and a Bukkit Multiworld plugin.
2. Place a RedNet Controller in that world.
3. Right-click placed controller to bring up the GUI.

Issue:
You are unable to change any configuration about the controller. The only working function is the page arrows. There is button is the lower right that only toggles between "Reinitialize" and "Confirm" but seems to not do anything besides that. The list is scrollable but none of the contents are selectable.

I was able to confirm there are no problems using the controller in the "Overworld", "Nether", "End" and the "Moon". No errors or exceptions in console and the server is clean of any other minor/major bugs. All other parts of RedNet work in these worlds as far as I can tell.

**Comment by powercrystals** [comment] 2013-05-15 21:47
I believe a recent version of MCPC changed this so it should work now - can you please test with their latest and see? Thanks!

**Comment by BarelyAPrincess** [comment] 2013-05-17 05:45
I just updated to Build 400 of MCPC+ which is the latest I can test with MC 1.5.1 and is only like 8 builds ahead of the version I was using., So I can't easily test the latest of the latest unless I download MC 1.5.2 and manually install all the same Tekkit mods on both my client and some random testing server. I could make it easy by just installing MFReloaded with MCPC+ but either way that would be more work then it's worth.

As far as I can tell Build 400 is not any better. I will try again with a later version of MCPC+ once Tekkit releases a 1.5.2 or better version. I wonder if this is at all related to Chicken Chunks unloading MCPC+ created worlds, Apparently you have to set CC's Orphaned Chunk Cleanup Timer to 0/disabled in config to fix the problem.

**Comment by powercrystals** [comment] 2013-05-18 01:31
No, the issue is that bukkit multiworld wasn't changing world.provider.dimensionid, which I was relying on. Blood changed this in MCPC, but I guess he only did it for 1.5.2 (I didn't ask and he didn't say). I'm going to leave this open - I'll let you decide if/when it's actually fixed, or if that fix didn't work.

**Comment by bloodmc** [comment] 2013-05-18 03:54
Many of the MultiVerse/MultiWorld issues will be fixed in an upcoming release of MCPC+. I have reimplemented the way MCPC handles plugin created worlds from the ground up. Each new world created by a plugin such as Multiverse will now be handled the same as Forge. This should guarantee compatibility across all mods. These changes will also require a patch to Forge so when we do release the updated build you will be required to grab the latest Forge build that includes our changes.

Here is a teaser of what I currently have working : http://i.imgur.com/fy1GRLv.png

Just keep watch on our latest MCPC+ builds for info on MultiVerse changes. Feel free to create a ticket on our github  as well since this is an issue on our end.

**Comment by powercrystals** [comment] 2013-05-20 22:46
@ChioriGreene - have you had a chance to test this? Since the issue appears to be solved on MCPC's side, I'd like to close this, but I want feedback from you first if possible.

**Comment by BarelyAPrincess** [comment] 2013-05-20 23:08
I want to test it out but since their is no Tekkit released yet for 1.5.2, I would have to put together a 1.5.2 server and client with MCPC+ and MFR. I'm a bit short on time but I will try to do something ASAP.

**Comment by powercrystals** [comment] 2013-05-21 02:53
I spoke with blood and (see above) we agreed this issue should be reposted on their bugtracker. I'm going to close this here.

**Closed as completed by powercrystals** 2013-05-21 02:53 UTC
Labels: bug

**Comment by BarelyAPrincess** [comment] 2013-05-22 07:42
I will take a look at the 1.5.2 release once I get a chance and if the problem still exists I'll post it to the MCPC+ bug tracker. Thanks for the help.
