### ISSUE TITLE
RedNet cable mode-change target is inconsistent on t-junctions.

### ISSUE THREAD

**Issue by KirinDave** [powercrystals/MineFactoryReloaded#126] opened 2013-05-23 18:36 UTC
The rightclick target for rednet cable mode changing is very inconsistent when looking down on t-junctions, particularly when flying in creative. Often times both the color change behavior and the mode changing functionality will fire.

**Comment by powercrystals** [comment] 2013-05-24 03:18
What version? The mode change was really bad up until ~785? I think?

e: A screenshot of the 'bad' way of looking at it would be a huge help.

**Comment by KirinDave** [comment] 2013-05-24 03:20
817 is where I reproduced it.

On Thu, May 23, 2013 at 8:18 PM, powercrystals notifications@github.comwrote:

> What version? The mode change was really bad up until ~785? I think?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/powercrystals/MineFactoryReloaded/issues/126#issuecomment-18384635
> .

## 

## 

Dave Fayram
dfayram@gmail.com

**Comment by KirinDave** [comment] 2013-05-24 03:32
http://fayr.am/PAE5 is a screenshot of an example orientation where both functions are triggered on rightclick.

**Comment by powercrystals** [comment] 2013-05-26 05:20
Can anyone but you trigger this? I cannot reproduce this despite clicking at the cable from all kinds of angles. Maybe it's a lag thing; does it happen in SP too or just MP?

**Comment by powercrystals** [comment] 2013-05-31 01:17
This should be fixed in 903; reopen if it isn't.

**Closed as completed by powercrystals** 2013-05-31 01:17 UTC
Labels: bug
